insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('hut_6','hut','farm_house');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('tractor1_369','tractor','farm_house');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('granaryhouse1_375','granaryhouse','farm_house');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('power_house_9	power','house','farm_house');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('treehouse_11','treehouse','farm_house');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('farm_house1_374','farm_house','farm_house');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('colortree_15','colortree','farm_house');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('milkbottle_18','milkbottle','farm_house');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('tool1_19','tool','farm_house');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('tool3_21','tool','farm_house');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('waterbottle_22','waterbottle','farm_house');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('basket_24','basket','farm_house');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('tool4_25','Hammer','farm_house');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('tool5_26','Axe','farm_house');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('stone1_30','stone','farm_house');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('mango_1','mango','farm_house');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('wind_meal_02_220	wind','mill','farm_house');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('green_button_1','green_button','farm_house');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('red_button_2','red_button','farm_house');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('bucket_16','bucket','farm_house');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('well_166','well','farm_house');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('Hero','Hero','farm_house');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('Farmer','Farmer','farm_house');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('Lady','Lady','farm_house');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('farm_house_door_01_5','door','farm_house');