insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('bathroomwall_1_4_0','bathroomwall','house');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('commode_188','commode','house');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('Towel_527','Towel','house');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('mug_526','mug','house');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('tap_181','tap','house');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('bucket_182','bucket','house');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('shelf1_183','shelf1','house');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('sink_184','sink','house');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('obj7_185','toy','house');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('obj6_186','shampoo bottle','house');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('obj5_187','bottle','house');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('shelf2_190','shelf','house');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('obj12_197	tisue','paper','house');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('mirror_199','mirror','house');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('bathroomwindow_528','window','house');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('pillar_189','pillar','house');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('door_202','door','house');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('storage_205','shelf','house');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('stand_203','shelf','house');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('sofa_204','sofa','house');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('tv_207','tv','house');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('obj14_210','book','house');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('obj15_211','box','house');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('light_215','light','house');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('obj19_216','frame','house');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('fridge_283','fridge','house');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('basket_284','basket','house');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('obj21_287','apron','house');