insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('walltile3',' wall tiles','miningsupply');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('pillar','pillar','miningsupply');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('window','window','miningsupply');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('dooranimation1','door','miningsupply');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('ropebottom','rope','miningsupply');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('woodentorch','torch','miningsupply');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('trolley','trolley','miningsupply');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('spadesmall','spade','miningsupply');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('hammer','hammer','miningsupply');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('cartonbox','cartonbox','miningsupply');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('brush','brush','miningsupply');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('mininngsupply_outdoor','door','miningsupply');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('flame','flame','miningsupply');