# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Fiji' do
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'

  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Fiji

  target 'FijiTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Fiji-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Fiji-tvOS

  target 'Fiji-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
