var res = {
/*
    "Loading_Game_Screen_background" : "res/Loading_Game_Screen/Background.png",
    "Loading_Game_Screen_car" : "res/Loading_Game_Screen/Bus.png",
    "Loading_Game_Screen_tyre"  : "res/Loading_Game_Screen/Tyre.png",
    "Loading_Game_Screen_match" : "res/Loading_Game_Screen/Matching.png",
    "Loading_Game_Screen_t" : "res/Loading_Game_Screen/T.png",
    "Loading_Game_Screen_w" : "res/Loading_Game_Screen/W.png",
    "Loading_Game_Screen_i" : "res/Loading_Game_Screen/I.png",
    "Loading_Game_Screen_n" : "res/Loading_Game_Screen/N.png",

    "Level_Screen_background" : "res/Level_Screen/Background.png", 
    "Level_Screen_level1_button" : "res/Level_Screen/Level_01_Play_button.png",
    "Level_Screen_level2_button" : "res/Level_Screen/Level_02_Lock_Button.png", 
    "Level_Screen_level3_button" : "res/Level_Screen/Level_03_Lock_Button.png",
    "level_02_play_button" : "res/Level_Screen/level_02_play_button.png", 
    "level_03_play_button" : "res/Level_Screen/level_03_play_button.png",
    
    "level1round1_background" : "res/Round_01_72dpi/Background.png",
    "level1round1_water" : "res/Round_01_72dpi/Water_01.png",
    "level1round1_leftcrack" : "res/Round_01_72dpi/Left_Crack.png",
    "level1round1_rightcrack" : "res/Round_01_72dpi/Right_Crack.png",
    "level1round1_topcrack" : "res/Round_01_72dpi/Top_Crack.png",
    "level1round1_bottomcrack" : "res/Round_01_72dpi/Bottom_Crack.png",
    "level1round1_drop" : "res/Round_01_72dpi/Water_Drop.png",
    "level1round1_crack" : "res/Round_01_72dpi/Shape_Trans.png",
    "level1round1_cube" : "res/Round_01_72dpi/Cube.png",
    "level1round1_refresh" : "res/Round_01_72dpi/refresh.png",
    
    
    "level1round2_circle" : "res/Round_01_72dpi/Circle.png",
    "level1round2_circle_trans" : "res/Round_01_72dpi/Circle_Trans.png",
    "level1round2_pentagone" : "res/Round_01_72dpi/Pentagone.png",
    "level1round2_pentagone_trans" : "res/Round_01_72dpi/Pentagone_Trans.png",
    
    "level1round3_star" : "res/Round_01_72dpi/Star.png",
    "level1round3_star_trans" : "res/Round_01_72dpi/Star_Trans.png",
    "level1round3_tringle" : "res/Round_01_72dpi/Tringle.png",
    "level1round3_tringle_trans" : "res/Round_01_72dpi/Tringle_Trans.png",
    
    
    "level2round1_background" : "res/Game_Screen_02/Background.png",
    "level2round1_weight_uper" : "res/Game_Screen_02/Weight_Uper.png",
    "level2round1_weight_main" : "res/Game_Screen_02/Weight_Main.png",
    "level2round1_coin_01" : "res/Game_Screen_02/Coin_01.png",
    "level2round1_coin_02" : "res/Game_Screen_02/COin_02.png",
    "level2round1_coin_03" : "res/Game_Screen_02/Coin_03.png",
    "level2round1_coin_04" : "res/Game_Screen_02/Coin_04.png",
    "level2round1_coin_05" : "res/Game_Screen_02/COin_05.png",
    "level2round1_coin_06" : "res/Game_Screen_02/Coin_06.png",
    "level2round1_coin_07" : "res/Game_Screen_02/Coin_07.png",
    "level2round1_coin_08" : "res/Game_Screen_02/COin_08.png",
    "level2round1_coin_09" : "res/Game_Screen_02/Coin_09.png",
    
    "level2round1_Star_Green" : "res/Game_Screen_02/Star_Green.png",
    "level2round1_Star_Red" : "res/Game_Screen_02/Star_Red.png",
    "level2round1_Star_Yellow" : "res/Game_Screen_02/Star_Yellow.png",
    
    
    "level3round1_background" : "res/Level_03/Background.png",
    "level3round1_board" : "res/Level_03/Board.png",
    "level3round1_a" : "res/Level_03/A.png",
    "level3round1_b" : "res/Level_03/B.png",
    "level3round1_c" : "res/Level_03/C.png",
    "level3round1_d" : "res/Level_03/D.png",
    "level3round1_e" : "res/Level_03/E.png",
    "level3round1_f" : "res/Level_03/F.png",
    "level3round1_g" : "res/Level_03/G.png",
    "level3round1_h" : "res/Level_03/H.png",
    "level3round1_i" : "res/Level_03/I.png",
    "level3round1_j" : "res/Level_03/J.png",
    "level3round1_k" : "res/Level_03/K.png",
    "level3round1_l" : "res/Level_03/L.png",
    "level3round1_m" : "res/Level_03/M.png",
    "level3round1_n" : "res/Level_03/N.png",
    "level3round1_o" : "res/Level_03/O.png",
    "level3round1_p" : "res/Level_03/P.png",
    "level3round1_q" : "res/Level_03/Q.png",
    "level3round1_r" : "res/Level_03/R.png",
    "level3round1_s" : "res/Level_03/S.png",
    "level3round1_t" : "res/Level_03/T.png",
    "level3round1_u" : "res/Level_03/U.png",
    "level3round1_v" : "res/Level_03/V.png",
    "level3round1_w" : "res/Level_03/W.png",
    "level3round1_x" : "res/Level_03/X.png",
    "level3round1_y" : "res/Level_03/Y.png",
    "level3round1_z" : "res/Level_03/Z.png",     
    
    "level3round1_a_ball" : "res/Level_03/A_Ball.png",
    "level3round1_b_ball" : "res/Level_03/B_Ball.png",
    "level3round1_c_ball" : "res/Level_03/C_Ball.png",
    "level3round1_d_ball" : "res/Level_03/D_Ball.png",
    "level3round1_e_ball" : "res/Level_03/E_Ball.png",
    "level3round1_f_ball" : "res/Level_03/F_Ball.png",
    "level3round1_g_ball" : "res/Level_03/G_Ball.png",
    "level3round1_h_ball" : "res/Level_03/H_Ball.png",
    "level3round1_i_ball" : "res/Level_03/I_Ball.png",
    "level3round1_j_ball" : "res/Level_03/J_Ball.png",
    "level3round1_k_ball" : "res/Level_03/K_Ball.png",
    "level3round1_l_ball" : "res/Level_03/L_Ball.png",
    "level3round1_m_ball" : "res/Level_03/M_Ball.png",
    "level3round1_n_ball" : "res/Level_03/N_Ball.png",
    "level3round1_o_ball" : "res/Level_03/O_Ball.png",
    "level3round1_p_ball" : "res/Level_03/P_Ball.png",
    "level3round1_q_ball" : "res/Level_03/Q_Ball.png",
    "level3round1_r_ball" : "res/Level_03/R_Ball.png",
    "level3round1_s_ball" : "res/Level_03/S_Ball.png",
    "level3round1_t_ball" : "res/Level_03/T_Ball.png",
    "level3round1_u_ball" : "res/Level_03/U_Ball.png",
    "level3round1_v_ball" : "res/Level_03/V_Ball.png",
    "level3round1_w_ball" : "res/Level_03/W_Ball.png",
    "level3round1_x_ball" : "res/Level_03/X_Ball.png",
    "level3round1_y_ball" : "res/Level_03/Y_Ball.png",
    "level3round1_z_ball" : "res/Level_03/Z_Ball.png",     

    
    "level3round1_a_ping" : "res/Level_03/A_Ping.png",
    "level3round1_b_ping" : "res/Level_03/B_Ping.png",
    "level3round1_c_ping" : "res/Level_03/C_Ping.png",
    "level3round1_d_ping" : "res/Level_03/D_Ping.png",
    "level3round1_e_ping" : "res/Level_03/E_Ping.png",
    "level3round1_f_ping" : "res/Level_03/F_Ping.png",
    "level3round1_g_ping" : "res/Level_03/G_Ping.png",
    "level3round1_h_ping" : "res/Level_03/H_Ping.png",
    "level3round1_i_ping" : "res/Level_03/I_Ping.png",
    "level3round1_j_ping" : "res/Level_03/J_Ping.png",
    "level3round1_k_ping" : "res/Level_03/K_Ping.png",
    "level3round1_l_ping" : "res/Level_03/L_Ping.png",
    "level3round1_m_ping" : "res/Level_03/M_Ping.png",
    "level3round1_n_ping" : "res/Level_03/N_Ping.png",
    "level3round1_o_ping" : "res/Level_03/O_Ping.png",
    "level3round1_p_ping" : "res/Level_03/P_Ping.png",
    "level3round1_q_ping" : "res/Level_03/Q_Ping.png",
    "level3round1_r_ping" : "res/Level_03/R_Ping.png",
    "level3round1_s_ping" : "res/Level_03/S_Ping.png",
    "level3round1_t_ping" : "res/Level_03/T_Ping.png",
    "level3round1_u_ping" : "res/Level_03/U_Ping.png",
    "level3round1_v_ping" : "res/Level_03/V_Ping.png",
    "level3round1_w_ping" : "res/Level_03/W_Ping.png",
    "level3round1_x_ping" : "res/Level_03/X_Ping.png",
    "level3round1_y_ping" : "res/Level_03/Y_Ping.png",
    "level3round1_z_ping" : "res/Level_03/Z_Ping.png",
*/

    "a_Sound" : "res/sounds/A_Sound.wav",
    "b_Sound" : "res/sounds/B_Sound.wav",
    "c_Sound" : "res/sounds/C_Sound.wav",
    "d_Sound" : "res/sounds/D_Sound.wav",
    "e_Sound" : "res/sounds/E_Sound.wav",
    "f_Sound" : "res/sounds/F_Sound.wav",
    "g_Sound" : "res/sounds/G_Sound.wav",
    "h_Sound" : "res/sounds/H_Sound.wav",
    "i_Sound" : "res/sounds/I_Sound.wav",
    "j_Sound" : "res/sounds/J_Sound.wav",
    "k_Sound" : "res/sounds/K_Sound.wav",
    "l_Sound" : "res/sounds/L_Sound.wav",
    "m_Sound" : "res/sounds/M_Sound.wav",
    "n_Sound" : "res/sounds/N_Sound.wav",
    "o_Sound" : "res/sounds/O_Sound.wav",
    "p_Sound" : "res/sounds/P_Sound.wav",
    "q_Sound" : "res/sounds/Q_Sound.wav",
    "r_Sound" : "res/sounds/R_Sound.wav",
    "s_Sound" : "res/sounds/S_Sound.wav",
    "t_Sound" : "res/sounds/T_Sound.wav",
    "u_Sound" : "res/sounds/U_Sound.wav",
    "v_Sound" : "res/sounds/V_Sound.wav",
    "w_Sound" : "res/sounds/W_Sound.wav",
    "x_Sound" : "res/sounds/X_Sound.wav",
    "y_Sound" : "res/sounds/Y_Sound.wav",
    "z_Sound" : "res/sounds/Z_Sound.wav",
    

    "ball_Sound" : "res/sounds/Ball_Sound.mp3",
    "blast_Heavy" : "res/sounds/Blast_Heavy.mp3",
  
    fish_png : "res/Game_screen_01/Fish/Fish.png",
    fish_plist : "res/Game_screen_01/Fish/Fish.plist",
    fish_json : "res/Game_screen_01/Fish/MainScene.json",
    
    Water_png : "res/Game_screen_01/water/water_animation.png",
    Water_plist : "res/Game_screen_01/water/water_animation.plist",
    Water_json : "res/Game_screen_01/water/MainScene.json",
    
    Loading_background : "res/Loading_Screen/Loading_background.png",
    Loading_Screen_png : "res/Loading_Screen/Loading_Screen.png",
    Loading_Screen_plist : "res/Loading_Screen/Loading_Screen.plist",

    Level_screen_png : "res/Level_screen/Level_screen.png",
    Level_screen_plist : "res/Level_screen/Level_screen.plist",
    
    Game_screen_01_png : "res/Game_screen_01/Game_screen.png",
    Game_screen_01_plist : "res/Game_screen_01/Game_screen.plist",
    
    Game_screen_02_png : "res/Game_screen_02/Game_screen.png",
    Game_screen_02_plist : "res/Game_screen_02/Game_screen.plist",
    
    Game_screen_03_png : "res/Game_screen_03/Game_screen.png",
    Game_screen_03_plist : "res/Game_screen_03/Game_screen.plist"
 
};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}
