insert into NODE_WORD_MAPPING(NODE_NAME, WORD_IN_ENGLISH, SCENE_NAME) values ('hut_6','hut','farmhouse');
insert into NODE_WORD_MAPPING(NODE_NAME, WORD_IN_ENGLISH, SCENE_NAME) values ('tractor1_369','tractor','farmhouse');
insert into NODE_WORD_MAPPING(NODE_NAME, WORD_IN_ENGLISH, SCENE_NAME) values ('granaryhouse1_375','granaryhouse','farmhouse');
insert into NODE_WORD_MAPPING(NODE_NAME, WORD_IN_ENGLISH, SCENE_NAME) values ('power_house_9	power','house','farmhouse');
insert into NODE_WORD_MAPPING(NODE_NAME, WORD_IN_ENGLISH, SCENE_NAME) values ('treehouse_11','treehouse','farmhouse');
insert into NODE_WORD_MAPPING(NODE_NAME, WORD_IN_ENGLISH, SCENE_NAME) values ('farm_house1_374','farmhouse','farmhouse');
insert into NODE_WORD_MAPPING(NODE_NAME, WORD_IN_ENGLISH, SCENE_NAME) values ('colortree_15','colortree','farmhouse');
insert into NODE_WORD_MAPPING(NODE_NAME, WORD_IN_ENGLISH, SCENE_NAME) values ('milkbottle_18','milkbottle','farmhouse');
insert into NODE_WORD_MAPPING(NODE_NAME, WORD_IN_ENGLISH, SCENE_NAME) values ('tool1_19','tool','farmhouse');
insert into NODE_WORD_MAPPING(NODE_NAME, WORD_IN_ENGLISH, SCENE_NAME) values ('tool3_21','tool','farmhouse');
insert into NODE_WORD_MAPPING(NODE_NAME, WORD_IN_ENGLISH, SCENE_NAME) values ('waterbottle_22','waterbottle','farmhouse');
insert into NODE_WORD_MAPPING(NODE_NAME, WORD_IN_ENGLISH, SCENE_NAME) values ('basket_24','basket','farmhouse');
insert into NODE_WORD_MAPPING(NODE_NAME, WORD_IN_ENGLISH, SCENE_NAME) values ('tool4_25','Hammer','farmhouse');
insert into NODE_WORD_MAPPING(NODE_NAME, WORD_IN_ENGLISH, SCENE_NAME) values ('tool5_26','Axe','farmhouse');
insert into NODE_WORD_MAPPING(NODE_NAME, WORD_IN_ENGLISH, SCENE_NAME) values ('stone1_30','stone','farmhouse');
insert into NODE_WORD_MAPPING(NODE_NAME, WORD_IN_ENGLISH, SCENE_NAME) values ('mango_1','mango','farmhouse');
insert into NODE_WORD_MAPPING(NODE_NAME, WORD_IN_ENGLISH, SCENE_NAME) values ('wind_meal_02_220	wind','mill','farmhouse');
insert into NODE_WORD_MAPPING(NODE_NAME, WORD_IN_ENGLISH, SCENE_NAME) values ('green_button_1','green_button','farmhouse');
insert into NODE_WORD_MAPPING(NODE_NAME, WORD_IN_ENGLISH, SCENE_NAME) values ('red_button_2','red_button','farmhouse');
insert into NODE_WORD_MAPPING(NODE_NAME, WORD_IN_ENGLISH, SCENE_NAME) values ('bucket_16','bucket','farmhouse');
insert into NODE_WORD_MAPPING(NODE_NAME, WORD_IN_ENGLISH, SCENE_NAME) values ('well_166','well','farmhouse');
insert into NODE_WORD_MAPPING(NODE_NAME, WORD_IN_ENGLISH, SCENE_NAME) values ('Hero','Hero','farmhouse');
insert into NODE_WORD_MAPPING(NODE_NAME, WORD_IN_ENGLISH, SCENE_NAME) values ('Farmer','Farmer','farmhouse');
insert into NODE_WORD_MAPPING(NODE_NAME, WORD_IN_ENGLISH, SCENE_NAME) values ('Lady','Lady','farmhouse');
insert into NODE_WORD_MAPPING(NODE_NAME, WORD_IN_ENGLISH, SCENE_NAME) values ('farm_house_door_01_5','door','farmhouse');