insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('floor','floor','grocery');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('meatfridge_945','refrigerator','grocery');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('meatstand_944','stand','grocery');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('table_0','table_0','grocery');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('fan','fan','grocery');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('cartbacka_1232','bag','grocery');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('paperbag_1229','paperbag','grocery');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('door','door','grocery');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('apple','apple juice','grocery');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('milk_00','milk','grocery');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('grape','grape juice','grocery');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('orange_1','orange juice','grocery');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('bottle','bottle','grocery');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('paper_109','paper','grocery');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('box_9','box','grocery');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('handwashgreen_242','handwashgreen','grocery');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('pumpkin_839_0','pumpkin','grocery');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('radish_846','radish','grocery');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('spinach_870','spinach','grocery');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('tomato_879','tomato','grocery');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('cabbage_924','cabbage','grocery');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('corn_930','corn','grocery');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('standfuritfront_939','standfuritfront','grocery');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('prawn_946','prawn','grocery');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('fish_1186_0','fish','grocery');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('carb_1190_4_0','carb','grocery');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('chicken_1204','chicken','grocery');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('meat_1207','meat','grocery');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('steps_1225','steps','grocery');
insert into NODE_WORD_MAPPING(WORD_IN_ENGLISH, NODE_NAME, SCENE_NAME) values ('weightshow_1228','weighing machine','grocery');