python3 scripts/create_json_image_mappings.py res/airport
python3 scripts/create_json_image_mappings.py res/bank
python3 scripts/create_json_image_mappings.py res/barn_house
python3 scripts/create_json_image_mappings.py res/busstation
python3 scripts/create_json_image_mappings.py res/cafe
python3 scripts/create_json_image_mappings.py res/camp
python3 scripts/create_json_image_mappings.py res/camp_clothshop
python3 scripts/create_json_image_mappings.py res/camp_gym
python3 scripts/create_json_image_mappings.py res/camp_studio
python3 scripts/create_json_image_mappings.py res/city
python3 scripts/create_json_image_mappings.py res/City1
python3 scripts/create_json_image_mappings.py res/City2
python3 scripts/create_json_image_mappings.py res/City3
python3 scripts/create_json_image_mappings.py res/City4
python3 scripts/create_json_image_mappings.py res/City5
python3 scripts/create_json_image_mappings.py res/club
python3 scripts/create_json_image_mappings.py res/dramatheatre
python3 scripts/create_json_image_mappings.py res/electricalshop
python3 scripts/create_json_image_mappings.py res/farmhouse
python3 scripts/create_json_image_mappings.py res/farmhouse_inside
python3 scripts/create_json_image_mappings.py res/firestation
python3 scripts/create_json_image_mappings.py res/granary
python3 scripts/create_json_image_mappings.py res/grocery
python3 scripts/create_json_image_mappings.py res/gym
python3 scripts/create_json_image_mappings.py res/hospital
python3 scripts/create_json_image_mappings.py res/house
python3 scripts/create_json_image_mappings.py res/locker
python3 scripts/create_json_image_mappings.py res/miningbar
python3 scripts/create_json_image_mappings.py res/miningbg
python3 scripts/create_json_image_mappings.py res/miningrailway
python3 scripts/create_json_image_mappings.py res/miningsupply
python3 scripts/create_json_image_mappings.py res/movietheater
python3 scripts/create_json_image_mappings.py res/office
python3 scripts/create_json_image_mappings.py res/park
python3 scripts/create_json_image_mappings.py res/parlour
python3 scripts/create_json_image_mappings.py res/policestation
python3 scripts/create_json_image_mappings.py res/postoffice
python3 scripts/create_json_image_mappings.py res/school
python3 scripts/create_json_image_mappings.py res/trainstationinside